### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by claudermilk** [LesserSpottedAustralianSquirel/voron_trident_pics#1]
Found discrepancies in the PDF:
Pg 4, b_drive_frame_upper.stl: I have it on pg 38.
Pg 5, z_rear_extrusionbracket_right.stl: I have it on pg 55.
Pg 8-10: The XY Joints & Carriage are weird. They have a line drawing exactly like the photo on pg 98. Not sure why, but I'd ignore it and have the following notations:
 xy_joint_left_lower_MGN12.stl on pg 106
 xy_joint_left_upper_MGN12.stl on pg 105
 xy_joint_right_lower_MGN12.stl on pg 102
 xy_joint_right_upper_MGN12.stl on pg 101
 x_carriage_frame_left.stl on pg 100
 x_carriage_frame_right.stl on pg 100
Pg 10, last item: Yep that looks like the thermal fuse, I'd delete this entry.
Pg 14, blower_housing_rear.stl: I have it on pg 166 (it's the fans that are colored blue, but the part makes its first appearance here)
Pg 14, hotend_fan_mount.stl: Same as above. I have it on pg 166.
Pg 15, cable_frame_anchor_x6.stl: I think this is the wrong item. Should be deck_support_3mm.stl or deck_support_4mm.stl from the Panels directory.
Pg 16, raspberrypi_bracket.stl: I have it on pg 189. (typo?)
Pg 17, lrs_psu_bracket_x2.stl: This is the wrong item. Should be rs_25_psu_bracket.stl.
Pg 17: Missing the parts from ElectronicsBay/Controller_Board for pg 193.
Pg 17: The springloaded part isn't printed. 
Pg 17: raspberrypi_bracket.stl: Not needed, this is just installing the Pi. Part was seen earlier. Delete entry.
Pg 17: Pg 202 reference: Yes, this is installing the controller board. Delete entry.
Pg 19, LED screen pg 234. Not a printed part. Delete entry.
Pg 19, "round thing" is the encoder knob that comes with the 12864 screen. Delete entry (though it's sad to lose the joke).
Pg 21: missing entry for side_skirt_b_250.stl seen on pg 242.
Pg 21: missing entry for bottom_panel_clip_4mm_x8.stl seen on pg 250.
Pg 23, latch_x2.stl: Duplicate entry, delete.

**Comment by LesserSpottedAustralianSquirel** [comment]
>Pg 4, b_drive_frame_upper.stl: I have it on pg 38.

Correct, updated as directed.

>Pg 5, z_rear_extrusionbracket_right.stl: I have it on pg 55.

Correct, updated as directed.

> Pg 8-10: The XY Joints & Carriage are weird. They have a line drawing exactly like the photo on pg 98. Not sure why, but I'd ignore it and have the following notations:

I have to agree with you. Not happy.

xy_joint_left_lower_MGN12.stl on pg 106
xy_joint_left_upper_MGN12.stl on pg 105
xy_joint_right_lower_MGN12.stl on pg 102
xy_joint_right_upper_MGN12.stl on pg 101
x_carriage_frame_left.stl on pg 100
x_carriage_frame_right.stl on pg 100

Done as requested. Reordered.

>Pg 10, last item: Yep that looks like the thermal fuse, I'd delete this entry.

Thanks for confirmation. I am going to leave it in as I did 3 table scans of the stls before I realised that it was a thermal fuse. 
If I made the mistake. Then I would like to save someone else the frustration. But you are right it should not be here.

>Pg 14, blower_housing_rear.stl: I have it on pg 166 (it's the fans that are colored blue, but the part makes its first appearance here)

Correct, updated as directed.  Also Reordered.

>Pg 14, hotend_fan_mount.stl: Same as above. I have it on pg 166.

Correct, updated as directed.  Also Reordered.

>Pg 15, cable_frame_anchor_x6.stl: I think this is the wrong item. Should be deck_support_3mm.stl or deck_support_4mm.stl from the Panels directory.

I originally had the parts you describe in this block. Can you confirm this correction? 
Ie have you built this far? I am on page 100 and yet to have the privilege.
Action: Added the parts you describe with a question to whether it is correct. 
I am going to leave this as a question but I am 99% sure you are right.
Also will need to find where this part does come up.

Thanks 

>Pg 16, raspberrypi_bracket.stl: I have it on pg 189. (typo?)

Correct, updated as directed.

>Pg 17, lrs_psu_bracket_x2.stl: This is the wrong item. Should be rs_25_psu_bracket.stl.

I am looking at them side by side and I have to say "how can you tell?"
On the other hand it does say, quite clearly, RS25-5 psu
Differed to obviously greater intelligence. 
Updated as directed.

>Pg 17: Missing the parts from ElectronicsBay/Controller_Board for pg 193.

Differed to obviously greater intelligence. updated as directed.

>Pg 17: The springloaded part isn't printed.

I am going to leave it in as I did 5 table scans of the stls before I considered it was not a STL. 
If I made the mistake. Then I would like to save someone else the frustration. But you are right it should not be here.

>Pg 17: raspberrypi_bracket.stl: Not needed, this is just installing the Pi. Part was seen earlier. Delete entry.

Done

>Pg 17: Pg 202 reference: Yes, this is installing the controller board. Delete entry.

Differed to obviously greater intelligence. updated as directed.

>Pg 19, LED screen pg 234. Not a printed part. Delete entry.

The part was [a]_mini12864_case_front_insert.stl and I found it. Added to doco
Thanks for bringing this to my attention.

>Pg 19, "round thing" is the encoder knob that comes with the 12864 screen. Delete entry (though it's sad to lose the joke).

Item deleted. No really it's gone. Honestly. You can trust me. No need to check.

>Pg 21: missing entry for side_skirt_b_250.stl seen on pg 242.

Wrong directory to. STLs/Skirt changed to STLs/Skirt/250
Yep. Now I understand. Thanks. Change added 

>Pg 21: missing entry for bottom_panel_clip_4mm_x8.stl seen on pg 250.

Sorry, can't see it. File not found. the only entry with "bottom_panel" is ./Panels/bottom_panel_clip_x4.stl
I am going with that. Please advise if I have it right.
Entry added. Possibly the wrong one.

>Pg 23, latch_x2.stl: Duplicate entry, delete.

Done. Grin.

Paris
In The
The spring

Extra: Any idea where [a]_y_endstop_housing.stl goes from STLs/Gantry/AB_Drive_Units. Can't find in manual. Looks important. Page number from official manual would be great.

Extra: added you to the credits. - thanks for your help.

**Comment by claudermilk** [comment]
> > Pg 15, cable_frame_anchor_x6.stl: I think this is the wrong item. Should be deck_support_3mm.stl or deck_support_4mm.stl from the Panels directory.
> 
> I originally had the parts you describe in this block. Can you confirm this correction? Ie have you built this far? I am on page 100 and yet to have the privilege. Action: Added the parts you describe with a question to whether it is correct. I am going to leave this as a question but I am 99% sure you are right. Also will need to find where this part does come up.
> 
> Thanks
Here's where the STL is in the repository: https://github.com/VoronDesign/Voron-Trident/blob/main/STLs/Panels/deck_support_3mm_x8.stl
Looks just like the picture; if you look closely you will see the main section is rectangular. I watched Steve's build series, and IIRC these are what he used. The page is also titled Deck Panel. The cable ties are shown on page 185 of the manual.

> > Pg 17, lrs_psu_bracket_x2.stl: This is the wrong item. Should be rs_25_psu_bracket.stl.
> 
> I am looking at them side by side and I have to say "how can you tell?" On the other hand it does say, quite clearly, RS25-5 psu Differed to obviously greater intelligence. Updated as directed.
Since I spent a while debating how I plan to hook up the RPi, I examined this a lot. I wanted to be as certain as I could I am eliminating the right parts (I'm going with the controller-to-GPIO route). Page 191 of the manual specifies the 5V power supply and page 192 specifies the 24V one. Also, the 5V is small & only needs the one bracket.

> > Pg 21: missing entry for bottom_panel_clip_4mm_x8.stl seen on pg 250.
> 
> Sorry, can't see it. File not found. the only entry with "bottom_panel" is ./Panels/bottom_panel_clip_x4.stl I am going with that. Please advise if I have it right. Entry added. Possibly the wrong one.
Oops, I mistyped the name; yes ./Panels/bottom_panel_clip_x4.stl is what it should be.

> Extra: Any idea where [a]_y_endstop_housing.stl goes from STLs/Gantry/AB_Drive_Units. Can't find in manual. Looks important. Page number from official manual would be great.
I have no clue. I've looked high and low for that and cannot find it. Additionally, the Y endstop is held within the [a]_endstop_pod_microswitch.stl part in the Gantry/X_Axis/XY_Joints directory.

> Extra: added you to the credits. - thanks for your help.
No problem, glad I could help.

**Comment by LesserSpottedAustralianSquirel** [comment]
Done as requested. Again thanks muchly for your help
